/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas1;

import javax.swing.JOptionPane;

/**
 *
 * @author Duita
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jenkel = new javax.swing.JPanel();
        form = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        jankel = new javax.swing.JLabel();
        combolaki = new javax.swing.JRadioButton();
        combocewe = new javax.swing.JRadioButton();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        txtSimpan = new javax.swing.JButton();
        txtBatal = new javax.swing.JButton();
        txtAgama = new javax.swing.JLabel();
        comboAgama = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jenkel.setBackground(new java.awt.Color(51, 204, 255));

        form.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        form.setText("Biodata Siswa");

        nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nama.setText("Nama :");

        nim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nim.setText("Nim :");

        jankel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jankel.setText("Jenis Kelamin :");

        buttonGroup1.add(combolaki);
        combolaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combolaki.setText("Laki-laki");

        buttonGroup1.add(combocewe);
        combocewe.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combocewe.setText("Perempuan");

        txtSimpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSimpan.setText("Simpan");
        txtSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSimpanMouseClicked(evt);
            }
        });
        txtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSimpanActionPerformed(evt);
            }
        });

        txtBatal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtBatal.setText("Batal");
        txtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatalActionPerformed(evt);
            }
        });

        txtAgama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAgama.setText("Agama");

        comboAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katholik", "Buddha" }));
        comboAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAgamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenkelLayout = new javax.swing.GroupLayout(jenkel);
        jenkel.setLayout(jenkelLayout);
        jenkelLayout.setHorizontalGroup(
            jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenkelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenkelLayout.createSequentialGroup()
                        .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jenkelLayout.createSequentialGroup()
                                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nama)
                                    .addComponent(nim))
                                .addGap(113, 113, 113)
                                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combocewe)
                                    .addComponent(combolaki)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jankel)
                            .addComponent(txtAgama))
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenkelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenkelLayout.createSequentialGroup()
                                .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jenkelLayout.createSequentialGroup()
                                .addComponent(txtSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(txtBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))))))
        );
        jenkelLayout.setVerticalGroup(
            jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenkelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form)
                .addGap(32, 32, 32)
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jankel)
                    .addComponent(combolaki))
                .addGap(18, 18, 18)
                .addComponent(combocewe)
                .addGap(9, 9, 9)
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgama)
                    .addComponent(comboAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jenkelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSimpan)
                    .addComponent(txtBatal))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jenkel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSimpanMouseClicked
        
    }//GEN-LAST:event_txtSimpanMouseClicked

    private void txtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSimpanActionPerformed
        // TODO add your handling code here:
        
        if (txtNama.getText().length()==0 || txtNim.getText().length()==0 )
        {
        JOptionPane.showMessageDialog(this,"Kolom Tidak Boleh Kosong");  
        }
        String jenkel = "";
        if (combolaki.isSelected()){
            jenkel = combolaki.getText();
        }else{
            jenkel = combocewe.getText();
        }
    String nama = txtNama.getText();
    String nim = txtNim.getText();
    String pesan = ""+jenkel+"\n";
    String religion = (String)comboAgama.getSelectedItem();
    JOptionPane.showMessageDialog(this,nama+"\n"+nim+"\n"+pesan+""+religion);
     
    }//GEN-LAST:event_txtSimpanActionPerformed

    private void comboAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAgamaActionPerformed
    // TODO add your handling code here:
        
    }//GEN-LAST:event_comboAgamaActionPerformed

    private void txtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatalActionPerformed
    // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtBatalActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboAgama;
    private javax.swing.JRadioButton combocewe;
    private javax.swing.JRadioButton combolaki;
    private javax.swing.JLabel form;
    private javax.swing.JLabel jankel;
    private javax.swing.JPanel jenkel;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel txtAgama;
    private javax.swing.JButton txtBatal;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JButton txtSimpan;
    // End of variables declaration//GEN-END:variables
}
